language: go

env:
  - COVERALLS_TOKEN=YHGcr4OuiAswC5UTIWcZNk1pm6I8Xs2oo

go:
  - master

before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  # Setup coveralls integration
  - go get github.com/mattn/goveralls

install:
  - dep ensure

script: 
  - go test -v ./...
  - $GOPATH/bin/goveralls -v -service=travis-ci
